[package]
name = "pi_sdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
parry2d = "0.13"
log = "0.4"
lazy_static = "1.4"
allsorts = { version = "0.14", default-features = false,  features = ["flate2_rust", "outline"]}
ab_glyph_rasterizer = "0.1"
image = "0.24"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.5"
getrandom = { version = "0.2", features = ["js"]}
console_log = "1.0"
console_error_panic_hook = "0.1"
pi_share = "=0.4.7"

[dev-dependencies]
pi_wgpu = { registry = "yn", version = "0.1",features = ["use_wgpu"] }
bytemuck = { version = "1.4", features = [ "derive" ] }
naga = "0.12"
pollster = "0.3"
env_logger = "0.10"
winit = { registry = "yn", version = "0.27" }
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
debug = true

# [patch.yn]
# pi_wgpu = { path = "../pi_wgpu", }